### ISSUE TITLE
您好！您的博客无法访问，可否将文章迁移到CSDN或者掘金呢？

### ISSUE THREAD

**Issue by zhoujianli1016** [cuiyiming007/sunflowr-by-java#1]

**Comment by cuiyiming007** [comment]
您好，感谢您浏览项目。我尝试访问博客，没有问题。因为近1年时间比较忙碌，没有更行博客。在有时间的情况下，可以逐步备份到掘金。   
当我备份后，通知您。

**Comment by zhoujianli1016** [comment]
好吧，我这边尝试了 QQ浏览器和Chrome浏览器，都无法访问。
![QQ图片20200902195231](https://user-images.githubusercontent.com/22313845/91978044-12680a00-ed56-11ea-9b14-9406bfc41a37.png)
还是很谢谢您的

**Comment by cuiyiming007** [comment]
我找公司其他人员尝试访问也可以成功，不需要翻墙。分析可能是由于你的DNS污染原因。
我把几篇博客同步到掘金，你可以通过https://juejin.im/post/6868105062074286087 此链接访问这篇文章。
谢谢你的反馈~
